### PR TITLE
ppc64le templates

### PR DESCRIPTION
**Pull request by ramereth**
Finally work on merging this into master. This includes all of the ppc64/ppc64le templates I had been using on our openpower cluster where we build our own.

### CODE REVIEW

**Review by knightsamar — COMMENTED** [review]
@ramereth is the latest opensuse build that you made recently, not included in this ?

**Comment by ramereth** [comment]
@knightsamar It's in a separate branch that I will include once this gets merged.

**Comment by ramereth** [comment]
@knightsamar @jldugger @fahlmant any further comments? I'm going to go ahead and merge if not.

**Comment by fahlmant** [comment]
Looks good as far as I can tell.

**Review by jldugger — APPROVED** [review]

**Pull request merged**
