### PR TITLE
CentOS 6.9

### PR DESCRIPTION
**Pull request by ramereth**

### CODE REVIEW

**Comment by ramereth** [comment]
@knightsamar ping, please review this

**Comment by knightsamar** [comment]
@ramereth If this isn't urgent for prod release, I would like to pass it through the security and sanity test suite that should be done by next week (right, @tolvstaa ?).

**Comment by ramereth** [comment]
@knightsamar fine by me!

**Review by knightsamar — APPROVED** [review]

**Comment by knightsamar** [comment]
Let's merge this. Apart from getting the test suite ready, we will need other parts for the whole setup and that would take some time.

**Pull request merged**
